#!/bin/bash
#
################################################################################################
#Author: Kamlesh
#Date: 01.03.2021
#Description: This script will look at your current day and tell you the state of the backup
#Last Modified: 
################################################################################################

NOW=$(date +"%a")
case $NOW in
          Mon)
		echo "Full backup scheduled for Monday";;
	  Tue|Web|Thu|Fri)
		echo "Partial backup for other weekedays day";;
	  Sat|Sun)
		echo "No backup scheduled for weekend";;
	  *) echo "Invalid choice - Byyyee !!!" ;;
          
esac

