#!/bin/bash
#
##########################################################
#Author: Kamlesh
#Date: 01.03.2021
#Description: case statement
#Last Modified: 
##########################################################

echo
echo Please chose one of the option below
echo
echo 'a = Display Date and Time'
echo 'b = List file and directories'
echo 'c = List user logged in'
echo 'd = Check system uptime'

echo 
     	 read choices

	 case $choices in

a ) date;;
b ) ls;;
c ) who;;
d ) uptime;;
* ) echo Invalid choice - Bye
