#!/bin/bash
#
#Author: Kamlesh
#Date: 01.03.2021
#Description: Example of defining variable 

a=kamlesh
b=prajapati
c='Linux class'

echo "My fisrt name is $a"
echo "My last name is $b"
echo "My class name is $c"
